# https://docs.travis-ci.com/user/customizing-the-build
dist: bionic
language: node_js
node_js: 12
script: npm run -- vsce package --out purple-yolk.vsix
deploy:
  on:
    tags: true
  provider: script
  script: npm run -- vsce publish --packagePath purple-yolk.vsix --pat "$PAT"
  skip_cleanup: true
