# https://docs.travis-ci.com/user/customizing-the-build
dist: bionic
language: node_js
node_js: 12
script: npm run -- vsce package --out purple-yolk.vsix
deploy:
  - api_key: $GITHUB_PERSONAL_ACCESS_TOKEN
    file: purple-yolk.vsix
    on:
      tags: true
    provider: releases
    skip_cleanup: true
  - on:
      tags: true
    provider: script
    script: npm run -- vsce publish --packagePath purple-yolk.vsix --pat "$AZURE_PERSONAL_ACCESS_TOKEN"
    skip_cleanup: true
