name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 12 }
      - run: npm install
      - run: npm run -- vsce package --out purple-yolk.vsix
      - uses: actions/upload-artifact@v2
        with:
          name: purple-yolk-${{ github.sha }}.vsix
          path: purple-yolk.vsix
