name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 12 }
      - run: npm install
      - run: npm run -- vsce package --out purple-yolk.vsix
      - uses: actions/upload-artifact@v2
        with:
          name: purple-yolk-${{ github.sha }}.vsix
          path: purple-yolk.vsix
      - if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: application/vsix
          asset_name: purple-yolk-${{ github.event.release.tag_name }}.vsix
          asset_path: purple-yolk.vsix
          upload_url: ${{ github.event.release.upload_url }}
      - if: github.event_name == 'release'
        run: npm run -- vsce publish --packagePath purple-yolk.vsix --pat "${{ secrets.AZURE_PERSONAL_ACCESS_TOKEN }}"
